# Generated by Django 3.1.1 on 2021-04-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=100)),
                ('ContactNumber', models.IntegerField(max_length=10)),
                ('Gender', models.CharField(max_length=1)),
                ('address', models.TextField()),
            ],
        ),
    ]
