# Generated by Django 3.1.1 on 2021-04-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records_hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ContactNumber',
            field=models.IntegerField(),
        ),
    ]
