# Generated by Django 3.1.1 on 2021-04-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records_hotel', '0002_auto_20210425_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=100)),
            ],
        ),
    ]
