# Generated by Django 3.1.1 on 2021-04-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records_hotel', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='ContactNumber',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
