# Generated by Django 3.1.1 on 2021-04-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records_hotel', '0004_auto_20210425_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ContactNumber',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CustomerName',
            field=models.CharField(max_length=50),
        ),
    ]
