# Generated by Django 3.1.1 on 2021-04-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records_hotel', '0005_auto_20210425_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='waiter',
            fields=[
                ('WaiterId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(max_length=10)),
                ('Gender', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='ContactNumber',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
