# Generated by Django 3.1.1 on 2021-04-25 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records_hotel', '0006_auto_20210425_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('ReservationID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Person_s', models.IntegerField()),
                ('R_time', models.DateTimeField(auto_now_add=True)),
                ('ContactNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records_hotel.customer')),
            ],
        ),
    ]
