# Generated by Django 3.1.1 on 2021-04-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records_hotel', '0007_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('Dishname', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
