# Generated by Django 3.1.1 on 2021-04-25 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records_hotel', '0008_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('OrderID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='Price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(default='food', max_length=20),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('TableID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Capacity', models.IntegerField()),
                ('Table_nos', models.IntegerField()),
                ('ReservationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records_hotel.reservation')),
                ('WaiterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records_hotel.waiter')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('TransationID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Amount', models.IntegerField()),
                ('ModeofPayment', models.CharField(max_length=20)),
                ('P_Time', models.DateTimeField(auto_now_add=True)),
                ('ContactNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records_hotel.customer')),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records_hotel.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='Dishname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records_hotel.menu'),
        ),
        migrations.AddField(
            model_name='order',
            name='TableID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records_hotel.table'),
        ),
    ]
