# Generated by Django 3.1.1 on 2021-04-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records_hotel', '0009_auto_20210425_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ContactNumber',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
