# Generated by Django 3.1.1 on 2021-04-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records_hotel', '0010_auto_20210426_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiter',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
